name: manage pull requests

on: pull_request

jobs:
  check:
    name: manage pull request
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: install required packages
        run: sudo apt-get update && sudo apt-get install -y libpci-dev libvulkan-dev libwayland-dev libxrandr-dev libxcb-randr0-dev libdconf-dev libdbus-1-dev libmagickcore-6.q16-dev libxfconf-0-dev rpm librpm-dev libzstd-dev

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - name: configure project
        run: cmake -DBUILD_TESTS=On .

      - name: build project
        run: cmake --build . -j$(nproc) --target package

      - name: run fastfetch
        run: ./fastfetch --recache --disable-linewrap false --hide-cursor false --show-errors true

      - name: run flashfetch
        run: ./flashfetch

      - name: run tests
        run: ctest

      - name: perform CodeQL analysis
        uses: github/codeql-action/analyze@v1
